import Database    from 'better-sqlite3'
import type { Statement } from 'better-sqlite3'
import path        from 'path'
import fs          from 'fs'
import { randomUUID } from 'crypto'

// Ensure the data directory exists before opening the DB file.
// This means you never need to manually create it on the server.
const DATA_DIR = path.join(process.cwd(), 'data')
const DB_PATH  = path.join(DATA_DIR, 'jobsift.db')
fs.mkdirSync(DATA_DIR, { recursive: true })

export const db = new Database(DB_PATH)

export function initDatabase(): void {
  // WAL mode: readers don't block writers — important for concurrent requests
  db.pragma('journal_mode = WAL')
  db.pragma('foreign_keys = ON')

  // ── devices ───────────────────────────────────────────────────────────────
  // One row per extension install (UUID generated by the extension on first run)
  db.exec(`
    CREATE TABLE IF NOT EXISTS devices (
      id         TEXT PRIMARY KEY,
      first_seen TEXT NOT NULL DEFAULT (datetime('now')),
      last_seen  TEXT NOT NULL DEFAULT (datetime('now'))
    )
  `)

  // ── usage ─────────────────────────────────────────────────────────────────
  // One row per (device, day). Primary key resets naturally — no cron needed.
  // A device that doesn't call the API today has no row today.
  db.exec(`
    CREATE TABLE IF NOT EXISTS usage (
      device_id     TEXT NOT NULL REFERENCES devices(id),
      date          TEXT NOT NULL DEFAULT (date('now')),
      batch_calls   INTEGER NOT NULL DEFAULT 0,
      analyze_calls INTEGER NOT NULL DEFAULT 0,
      profile_calls INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (device_id, date)
    )
  `)

  // ── request_logs ──────────────────────────────────────────────────────────
  // Every API request is logged: who, what, how long, did it succeed.
  db.exec(`
    CREATE TABLE IF NOT EXISTS request_logs (
      id         TEXT PRIMARY KEY,
      device_id  TEXT,
      endpoint   TEXT NOT NULL,
      latency_ms INTEGER NOT NULL,
      status     INTEGER NOT NULL,
      error      TEXT    DEFAULT NULL,
      created_at TEXT    NOT NULL DEFAULT (datetime('now'))
    )
  `)

  // Indexes for the admin queries
  db.exec(`CREATE INDEX IF NOT EXISTS idx_usage_date     ON usage (date)`)
  db.exec(`CREATE INDEX IF NOT EXISTS idx_logs_created   ON request_logs (created_at)`)
  db.exec(`CREATE INDEX IF NOT EXISTS idx_logs_device    ON request_logs (device_id)`)
  db.exec(`CREATE INDEX IF NOT EXISTS idx_logs_status    ON request_logs (status)`)

  // Prepare all statements now that tables are guaranteed to exist.
  // Must be called here — not at module load — because better-sqlite3 compiles
  // SQL immediately on db.prepare() and would crash if the table doesn't exist.
  _initStatements()

  console.log('Database initialized')
}

// ── Prepared statements ────────────────────────────────────────────────────────
// Null until _initStatements() is called from initDatabase().
type Stmt = Statement<unknown[]>

let stmtUpsertDevice:  Stmt | null = null
let stmtGetUsage:      Stmt | null = null
let stmtIncrBatch:     Stmt | null = null
let stmtIncrAnalyze:   Stmt | null = null
let stmtIncrProfile:   Stmt | null = null
let stmtInsertLog:     Stmt | null = null

function _initStatements(): void {
  stmtUpsertDevice = db.prepare(`
    INSERT INTO devices (id) VALUES (?)
    ON CONFLICT(id) DO UPDATE SET last_seen = datetime('now')
  `)

  stmtGetUsage = db.prepare(`
    SELECT batch_calls, analyze_calls, profile_calls
    FROM   usage
    WHERE  device_id = ? AND date = date('now')
  `)

  // INSERT OR IGNORE + UPDATE pattern works on all SQLite versions
  stmtIncrBatch = db.prepare(`
    INSERT INTO usage (device_id, batch_calls) VALUES (?, 1)
    ON CONFLICT(device_id, date) DO UPDATE SET batch_calls = batch_calls + 1
  `)

  stmtIncrAnalyze = db.prepare(`
    INSERT INTO usage (device_id, analyze_calls) VALUES (?, 1)
    ON CONFLICT(device_id, date) DO UPDATE SET analyze_calls = analyze_calls + 1
  `)

  stmtIncrProfile = db.prepare(`
    INSERT INTO usage (device_id, profile_calls) VALUES (?, 1)
    ON CONFLICT(device_id, date) DO UPDATE SET profile_calls = profile_calls + 1
  `)

  stmtInsertLog = db.prepare(`
    INSERT INTO request_logs (id, device_id, endpoint, latency_ms, status, error)
    VALUES (@id, @deviceId, @endpoint, @latencyMs, @status, @error)
  `)
}

// ── Public helpers ─────────────────────────────────────────────────────────────

export function upsertDevice(id: string): void {
  stmtUpsertDevice?.run(id)
}

export interface UsageRow {
  batch_calls:   number
  analyze_calls: number
  profile_calls: number
}

export function getUsageToday(deviceId: string): UsageRow {
  const row = stmtGetUsage?.get(deviceId) as UsageRow | undefined
  return row ?? { batch_calls: 0, analyze_calls: 0, profile_calls: 0 }
}

export type UsageType = 'batch' | 'analyze' | 'profile'

export function incrementUsage(deviceId: string, type: UsageType): void {
  if (type === 'batch')   stmtIncrBatch?.run(deviceId)
  if (type === 'analyze') stmtIncrAnalyze?.run(deviceId)
  if (type === 'profile') stmtIncrProfile?.run(deviceId)
}

export interface LogEntry {
  deviceId:  string | null
  endpoint:  string
  latencyMs: number
  status:    number
  error?:    string
}

export function logRequest(entry: LogEntry): void {
  try {
    stmtInsertLog?.run({
      id:        randomUUID(),
      deviceId:  entry.deviceId ?? null,
      endpoint:  entry.endpoint,
      latencyMs: entry.latencyMs,
      status:    entry.status,
      error:     entry.error ?? null,
    })
  } catch (err) {
    // Log failures must never crash the request — swallow silently
    console.error('Failed to write request log:', err)
  }
}
